//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Core.Input
{
    public partial class @Controls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Controls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""c08e998a-6331-45e5-8e29-8b8d1803f5d5"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""20fbd17f-bd66-4119-938f-373ffb3ff8d7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDown"",
                    ""type"": ""Button"",
                    ""id"": ""f0083a93-fd69-4e35-b3f5-db8d6dc50ef0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseUp"",
                    ""type"": ""Button"",
                    ""id"": ""16f8579f-5bc6-48c7-a027-0c6cc20ab62d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""d9c7fa9b-d526-4118-9d10-3cd15b88f666"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomScroll"",
                    ""type"": ""Value"",
                    ""id"": ""aaf40730-3a1a-47c4-8bfa-9a1777a2a5a4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraMove"",
                    ""type"": ""Value"",
                    ""id"": ""7b878baf-1413-4717-a79e-e6ed21f81904"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraTurn"",
                    ""type"": ""Value"",
                    ""id"": ""3c573929-64f7-4dd5-8ad5-3eaad8b9bb23"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NextUnitPressed"",
                    ""type"": ""Button"",
                    ""id"": ""badfddef-5461-4580-a4b8-aff6988ee17f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num1Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""6fc07ad5-59ac-4fd8-8c5c-b096049a1a2d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num2Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""69c5c8fc-1d9f-402c-a702-901c85c9289e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num3Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""14c9367c-4410-4d87-a415-da54545cfa05"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num4Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""dfeb13ec-9069-4d7c-b8fa-f98a4eb54207"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num5Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""676bbf60-252d-4c85-9e78-f20a80d2a7c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num6Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""05f0e6e3-9d27-48c5-8807-fb69bab1d0ed"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num7Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""65fd0754-2182-4c1d-98b7-c69137fa0981"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num8Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""205c0ff1-d92b-4aff-aba8-ef643d2080f1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Num9Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""9c57308b-adec-4174-962b-7578813bfd40"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""255be60f-dac2-4ee0-bb2e-110a8ec4d47b"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22eb8355-d878-4fe6-9689-6eea9b0e9787"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""MouseDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""788efeb7-f887-4085-8be1-0d2ae830dc33"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50b90715-9ab4-45fe-afda-44d0fbc9eaf3"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""ZoomScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfcd833b-b863-455d-b18e-28cb6b2496c3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""01bc3f05-e647-4d62-8df0-df94482518ed"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""602e5000-efd6-423e-bb08-113842bd435b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9f83eea4-860b-42b0-9573-b2f37bcb59da"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2a6d6567-efb3-4e8e-83cb-5a0f9f00f2d6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6de3f5d2-cf64-4e55-9b94-c2ae63945af6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""bf72bbd1-c029-4829-a4c5-91c4b46ec06f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c98b8502-5d05-4168-99b5-aa4cff113042"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4fdaf0a0-ead7-48a3-8cb4-599b5add1fde"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4f68efbf-d891-4d09-ba58-01ebf6a4aca6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""82b55e7d-e9c7-4c10-a254-9591b212c7a3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QandE"",
                    ""id"": ""cf808b16-3d53-4a93-b0a8-8fb2ecab98e1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraTurn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b7bef7a9-1cfb-43ee-9075-779864cf75c5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""75f7bb2b-ba68-4e9f-a41c-8ae7e4c7eec7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""CameraTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8baf45cc-a05e-44d0-8b1d-dac5f3fbaa85"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""NextUnitPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1655f22f-9952-4157-a21f-2f5948e8822c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num1Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dffc02b5-fb6d-4e49-8340-ea36e3dbe4ac"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num1Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""857bb54d-7829-4d0c-8287-b3d964338c39"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num2Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46a5bb8f-b6f2-42fd-b0a3-a6d15d49bb36"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num2Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bb73ef9-30b7-4818-a73d-98f67a1933cc"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num3Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae679496-3549-4c60-8f27-094edabb664f"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num3Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e50a4b58-97a2-4dea-8568-e36a9b8b9ebc"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num4Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15c9b501-9d8b-4712-932b-2d7d7988765e"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num4Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd432972-d775-4402-86d7-9e0c0f4a5b64"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num5Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c96ad06-214a-4b71-925a-25479a336412"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num5Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce3b9d7e-2133-452b-9c31-c46018aafda8"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num6Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67a7db8e-e4cd-47f0-806c-42095ad03721"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num6Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c56867e4-2463-4b56-b1a0-c272afdb63d3"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num7Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7202a9ce-e68b-4ad6-b502-cd3397e98e2b"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num7Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55fb8a18-d823-425d-9bc2-e3bf983a23b7"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num8Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc2cb9cf-8eb3-4bd6-a374-d135b679b974"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num8Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2329e92-8a2a-4b38-9a45-0e3b879da963"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num9Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08acf37e-1abf-457e-9f24-33569582eb9f"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""Num9Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_MousePosition = m_Player.FindAction("MousePosition", throwIfNotFound: true);
            m_Player_MouseDown = m_Player.FindAction("MouseDown", throwIfNotFound: true);
            m_Player_MouseUp = m_Player.FindAction("MouseUp", throwIfNotFound: true);
            m_Player_RightClick = m_Player.FindAction("RightClick", throwIfNotFound: true);
            m_Player_ZoomScroll = m_Player.FindAction("ZoomScroll", throwIfNotFound: true);
            m_Player_CameraMove = m_Player.FindAction("CameraMove", throwIfNotFound: true);
            m_Player_CameraTurn = m_Player.FindAction("CameraTurn", throwIfNotFound: true);
            m_Player_NextUnitPressed = m_Player.FindAction("NextUnitPressed", throwIfNotFound: true);
            m_Player_Num1Pressed = m_Player.FindAction("Num1Pressed", throwIfNotFound: true);
            m_Player_Num2Pressed = m_Player.FindAction("Num2Pressed", throwIfNotFound: true);
            m_Player_Num3Pressed = m_Player.FindAction("Num3Pressed", throwIfNotFound: true);
            m_Player_Num4Pressed = m_Player.FindAction("Num4Pressed", throwIfNotFound: true);
            m_Player_Num5Pressed = m_Player.FindAction("Num5Pressed", throwIfNotFound: true);
            m_Player_Num6Pressed = m_Player.FindAction("Num6Pressed", throwIfNotFound: true);
            m_Player_Num7Pressed = m_Player.FindAction("Num7Pressed", throwIfNotFound: true);
            m_Player_Num8Pressed = m_Player.FindAction("Num8Pressed", throwIfNotFound: true);
            m_Player_Num9Pressed = m_Player.FindAction("Num9Pressed", throwIfNotFound: true);
        }

        ~@Controls()
        {
            UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, Controls.Player.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
        private readonly InputAction m_Player_MousePosition;
        private readonly InputAction m_Player_MouseDown;
        private readonly InputAction m_Player_MouseUp;
        private readonly InputAction m_Player_RightClick;
        private readonly InputAction m_Player_ZoomScroll;
        private readonly InputAction m_Player_CameraMove;
        private readonly InputAction m_Player_CameraTurn;
        private readonly InputAction m_Player_NextUnitPressed;
        private readonly InputAction m_Player_Num1Pressed;
        private readonly InputAction m_Player_Num2Pressed;
        private readonly InputAction m_Player_Num3Pressed;
        private readonly InputAction m_Player_Num4Pressed;
        private readonly InputAction m_Player_Num5Pressed;
        private readonly InputAction m_Player_Num6Pressed;
        private readonly InputAction m_Player_Num7Pressed;
        private readonly InputAction m_Player_Num8Pressed;
        private readonly InputAction m_Player_Num9Pressed;
        public struct PlayerActions
        {
            private @Controls m_Wrapper;
            public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @MousePosition => m_Wrapper.m_Player_MousePosition;
            public InputAction @MouseDown => m_Wrapper.m_Player_MouseDown;
            public InputAction @MouseUp => m_Wrapper.m_Player_MouseUp;
            public InputAction @RightClick => m_Wrapper.m_Player_RightClick;
            public InputAction @ZoomScroll => m_Wrapper.m_Player_ZoomScroll;
            public InputAction @CameraMove => m_Wrapper.m_Player_CameraMove;
            public InputAction @CameraTurn => m_Wrapper.m_Player_CameraTurn;
            public InputAction @NextUnitPressed => m_Wrapper.m_Player_NextUnitPressed;
            public InputAction @Num1Pressed => m_Wrapper.m_Player_Num1Pressed;
            public InputAction @Num2Pressed => m_Wrapper.m_Player_Num2Pressed;
            public InputAction @Num3Pressed => m_Wrapper.m_Player_Num3Pressed;
            public InputAction @Num4Pressed => m_Wrapper.m_Player_Num4Pressed;
            public InputAction @Num5Pressed => m_Wrapper.m_Player_Num5Pressed;
            public InputAction @Num6Pressed => m_Wrapper.m_Player_Num6Pressed;
            public InputAction @Num7Pressed => m_Wrapper.m_Player_Num7Pressed;
            public InputAction @Num8Pressed => m_Wrapper.m_Player_Num8Pressed;
            public InputAction @Num9Pressed => m_Wrapper.m_Player_Num9Pressed;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void AddCallbacks(IPlayerActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @MouseDown.started += instance.OnMouseDown;
                @MouseDown.performed += instance.OnMouseDown;
                @MouseDown.canceled += instance.OnMouseDown;
                @MouseUp.started += instance.OnMouseUp;
                @MouseUp.performed += instance.OnMouseUp;
                @MouseUp.canceled += instance.OnMouseUp;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @ZoomScroll.started += instance.OnZoomScroll;
                @ZoomScroll.performed += instance.OnZoomScroll;
                @ZoomScroll.canceled += instance.OnZoomScroll;
                @CameraMove.started += instance.OnCameraMove;
                @CameraMove.performed += instance.OnCameraMove;
                @CameraMove.canceled += instance.OnCameraMove;
                @CameraTurn.started += instance.OnCameraTurn;
                @CameraTurn.performed += instance.OnCameraTurn;
                @CameraTurn.canceled += instance.OnCameraTurn;
                @NextUnitPressed.started += instance.OnNextUnitPressed;
                @NextUnitPressed.performed += instance.OnNextUnitPressed;
                @NextUnitPressed.canceled += instance.OnNextUnitPressed;
                @Num1Pressed.started += instance.OnNum1Pressed;
                @Num1Pressed.performed += instance.OnNum1Pressed;
                @Num1Pressed.canceled += instance.OnNum1Pressed;
                @Num2Pressed.started += instance.OnNum2Pressed;
                @Num2Pressed.performed += instance.OnNum2Pressed;
                @Num2Pressed.canceled += instance.OnNum2Pressed;
                @Num3Pressed.started += instance.OnNum3Pressed;
                @Num3Pressed.performed += instance.OnNum3Pressed;
                @Num3Pressed.canceled += instance.OnNum3Pressed;
                @Num4Pressed.started += instance.OnNum4Pressed;
                @Num4Pressed.performed += instance.OnNum4Pressed;
                @Num4Pressed.canceled += instance.OnNum4Pressed;
                @Num5Pressed.started += instance.OnNum5Pressed;
                @Num5Pressed.performed += instance.OnNum5Pressed;
                @Num5Pressed.canceled += instance.OnNum5Pressed;
                @Num6Pressed.started += instance.OnNum6Pressed;
                @Num6Pressed.performed += instance.OnNum6Pressed;
                @Num6Pressed.canceled += instance.OnNum6Pressed;
                @Num7Pressed.started += instance.OnNum7Pressed;
                @Num7Pressed.performed += instance.OnNum7Pressed;
                @Num7Pressed.canceled += instance.OnNum7Pressed;
                @Num8Pressed.started += instance.OnNum8Pressed;
                @Num8Pressed.performed += instance.OnNum8Pressed;
                @Num8Pressed.canceled += instance.OnNum8Pressed;
                @Num9Pressed.started += instance.OnNum9Pressed;
                @Num9Pressed.performed += instance.OnNum9Pressed;
                @Num9Pressed.canceled += instance.OnNum9Pressed;
            }

            private void UnregisterCallbacks(IPlayerActions instance)
            {
                @MousePosition.started -= instance.OnMousePosition;
                @MousePosition.performed -= instance.OnMousePosition;
                @MousePosition.canceled -= instance.OnMousePosition;
                @MouseDown.started -= instance.OnMouseDown;
                @MouseDown.performed -= instance.OnMouseDown;
                @MouseDown.canceled -= instance.OnMouseDown;
                @MouseUp.started -= instance.OnMouseUp;
                @MouseUp.performed -= instance.OnMouseUp;
                @MouseUp.canceled -= instance.OnMouseUp;
                @RightClick.started -= instance.OnRightClick;
                @RightClick.performed -= instance.OnRightClick;
                @RightClick.canceled -= instance.OnRightClick;
                @ZoomScroll.started -= instance.OnZoomScroll;
                @ZoomScroll.performed -= instance.OnZoomScroll;
                @ZoomScroll.canceled -= instance.OnZoomScroll;
                @CameraMove.started -= instance.OnCameraMove;
                @CameraMove.performed -= instance.OnCameraMove;
                @CameraMove.canceled -= instance.OnCameraMove;
                @CameraTurn.started -= instance.OnCameraTurn;
                @CameraTurn.performed -= instance.OnCameraTurn;
                @CameraTurn.canceled -= instance.OnCameraTurn;
                @NextUnitPressed.started -= instance.OnNextUnitPressed;
                @NextUnitPressed.performed -= instance.OnNextUnitPressed;
                @NextUnitPressed.canceled -= instance.OnNextUnitPressed;
                @Num1Pressed.started -= instance.OnNum1Pressed;
                @Num1Pressed.performed -= instance.OnNum1Pressed;
                @Num1Pressed.canceled -= instance.OnNum1Pressed;
                @Num2Pressed.started -= instance.OnNum2Pressed;
                @Num2Pressed.performed -= instance.OnNum2Pressed;
                @Num2Pressed.canceled -= instance.OnNum2Pressed;
                @Num3Pressed.started -= instance.OnNum3Pressed;
                @Num3Pressed.performed -= instance.OnNum3Pressed;
                @Num3Pressed.canceled -= instance.OnNum3Pressed;
                @Num4Pressed.started -= instance.OnNum4Pressed;
                @Num4Pressed.performed -= instance.OnNum4Pressed;
                @Num4Pressed.canceled -= instance.OnNum4Pressed;
                @Num5Pressed.started -= instance.OnNum5Pressed;
                @Num5Pressed.performed -= instance.OnNum5Pressed;
                @Num5Pressed.canceled -= instance.OnNum5Pressed;
                @Num6Pressed.started -= instance.OnNum6Pressed;
                @Num6Pressed.performed -= instance.OnNum6Pressed;
                @Num6Pressed.canceled -= instance.OnNum6Pressed;
                @Num7Pressed.started -= instance.OnNum7Pressed;
                @Num7Pressed.performed -= instance.OnNum7Pressed;
                @Num7Pressed.canceled -= instance.OnNum7Pressed;
                @Num8Pressed.started -= instance.OnNum8Pressed;
                @Num8Pressed.performed -= instance.OnNum8Pressed;
                @Num8Pressed.canceled -= instance.OnNum8Pressed;
                @Num9Pressed.started -= instance.OnNum9Pressed;
                @Num9Pressed.performed -= instance.OnNum9Pressed;
                @Num9Pressed.canceled -= instance.OnNum9Pressed;
            }

            public void RemoveCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayerActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PlayerActions @Player => new PlayerActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        public interface IPlayerActions
        {
            void OnMousePosition(InputAction.CallbackContext context);
            void OnMouseDown(InputAction.CallbackContext context);
            void OnMouseUp(InputAction.CallbackContext context);
            void OnRightClick(InputAction.CallbackContext context);
            void OnZoomScroll(InputAction.CallbackContext context);
            void OnCameraMove(InputAction.CallbackContext context);
            void OnCameraTurn(InputAction.CallbackContext context);
            void OnNextUnitPressed(InputAction.CallbackContext context);
            void OnNum1Pressed(InputAction.CallbackContext context);
            void OnNum2Pressed(InputAction.CallbackContext context);
            void OnNum3Pressed(InputAction.CallbackContext context);
            void OnNum4Pressed(InputAction.CallbackContext context);
            void OnNum5Pressed(InputAction.CallbackContext context);
            void OnNum6Pressed(InputAction.CallbackContext context);
            void OnNum7Pressed(InputAction.CallbackContext context);
            void OnNum8Pressed(InputAction.CallbackContext context);
            void OnNum9Pressed(InputAction.CallbackContext context);
        }
    }
}
